### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by Superspider** [mbaddeley/usdn#1]
Does this project have anything to do with μSDN mentioned in this article?
Santos L F D S , Mendonca F F D , Dias K L . μSDN: An SDN-Based Routing Architecture for Wireless Sensor Networks[C]// 2017 VII Brazilian Symposium on Computing Systems Engineering (SBESC). IEEE Computer Society, 2017

**Comment by mbaddeley** [comment]
Nope, this publication came out at exactly the same time we published our first μSDN paper. They just happened to use the same name. As far as I know there is no implementation of their one. 

[Isolating SDN control traffic with layer-2 slicing in 6TiSCH industrial IoT networks](https://ieeexplore.ieee.org/document/8169876) <--- our first μSDN paper.
