### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Superspider** [mbaddeley/usdn#2]
When I switched to the directory    `_/examples / SDN / conttoller`_  and executed the `make` instruction, an error occurred.
![s j 44rr 7 4cysc slxc7](https://user-images.githubusercontent.com/11975429/50198052-e12e8700-0384-11e9-971b-24a041319be2.png)

**Comment by mbaddeley** [comment]
Which branch? master?

Are you using the 20-bit compiler [here](https://github.com/pksec/msp430-gcc-4.7.3)?

**Comment by Superspider** [comment]
Thank you very much for your help. I have been able to run your project normally. Your work is very helpful to my research. Thank you sincerely！

**Comment by mbaddeley** [comment]
No problem, if you need any further help let me know!
