### ISSUE TITLE
When I turned to the directory '/examples / SDN / conttollers or nodes_ and executed the `make` instruction, an error. Furthermore, i did the both instructions but version msp430-gcc (GCC) 4.7.0 20120322 (mspgcc dev 20120716) not update it yet to 4.7.3

### ISSUE THREAD

**Issue by ghost** [mbaddeley/usdn#3]
user@instant-contiki:~/usdn/examples/sdn/controller$ make
using saved target 'exp5438'
obj_exp5438/stats.d=
mkdir obj_exp5438
  CC        ../../../apps/multiflow/multiflow.c
  CC        ../../../apps/atom/atom.c
  CC        ../../../apps/atom/atom-buffer.c
  CC        ../../../apps/atom/atom-net.c
  CC        ../../../apps/atom/atom-sb-usdn.c
  CC        ../../../apps/atom/atom-sb-rpl.c
  CC        ../../../apps/atom/atom-app-route-sp.c
  CC        ../../../apps/atom/atom-app-route-rpl.c
  CC        ../../../apps/atom/atom-app-join-cfg.c
  CC        ../../../platform/exp5438/./msp430.c
  CC        ../../../core/dev/leds.c
  CC        ../../../platform/exp5438/./watchdog.c
  CC        ../../../platform/exp5438/./spix.c
  CC        ../../../dev/cc2420/cc2420.c
  CC        ../../../platform/exp5438/./cc2420-arch.c
  CC        ../../../platform/exp5438/./rtimer-arch.c
  CC        ../../../platform/exp5438/./node-id.c
  CC        ../../../platform/exp5438/./leds-arch.c
  CC        ../../../platform/exp5438/./uart1x.c
  CC        ../../../platform/exp5438/./lcd.c
  CC        ../../../platform/exp5438/./hal_lcd.c
  CC        ../../../platform/exp5438/./hal_lcd_fonts.c
  CC        ../../../platform/exp5438/./duty-cycle-scroller.c
  CC        ../../../core/cfs/cfs-ram.c
  CC        ../../../platform/exp5438/./uart1-putchar.c
  CC        ../../../core/lib/me.c
  CC        ../../../core/lib/me_tabs.c
  CC        ../../../core/dev/slip.c
  CC        ../../../core/lib/crc16.c
  CC        ../../../platform/exp5438/./flash.c
  CC        ../../../platform/exp5438/./clock.c
  CC        ../../../cpu/msp430/./lpm.c
  CC        ../../../core/loader/elfloader.c
  CC        ../../../core/loader/elfloader-msp430.c
  CC        ../../../core/loader/symtab.c
  CC        ../../../core/net/sdn/sdn.c
  CC        ../../../core/net/sdn/sdn-cd.c
  CC        ../../../core/net/sdn/sdn-conf.c
  CC        ../../../core/net/sdn/sdn-ext-header.c
  CC        ../../../core/net/sdn/sdn-ft.c
  CC        ../../../core/net/sdn/sdn-packetbuf.c
  CC        ../../../core/net/sdn/usdn/usdn-adapter.c
  CC        ../../../core/net/sdn/usdn/usdn-driver.c
  CC        ../../../core/net/sdn/usdn/usdn-engine.c
  CC        ../../../core/sys/arg.c
  CC        ../../../core/sys/autostart.c
  CC        ../../../core/sys/compower.c
  CC        ../../../core/sys/ctimer.c
  CC        ../../../core/sys/energest.c
  CC        ../../../core/sys/etimer.c
  CC        ../../../core/sys/log-ng.c
  CC        ../../../core/sys/mt.c
  CC        ../../../core/sys/process.c
  CC        ../../../core/sys/procinit.c
  CC        ../../../core/sys/rtimer.c
  CC        ../../../core/sys/stimer.c
  CC        ../../../core/sys/timer.c
  CC        ../../../core/dev/nullradio.c
  CC        ../../../core/dev/serial-line.c
  CC        ../../../core/lib/aes-128.c
  CC        ../../../core/lib/assert.c
  CC        ../../../core/lib/ccm-star.c
  CC        ../../../core/lib/gcr.c
  CC        ../../../core/lib/ifft.c
  CC        ../../../core/lib/list.c
  CC        ../../../core/lib/memb.c
  CC        ../../../core/lib/mmem.c
  CC        ../../../core/lib/petsciiconv.c
obj_exp5438/stats.o=
  CC        ../../../core/lib/random.c
  CC        ../../../core/lib/ringbuf.c
  CC        ../../../core/lib/ringbufindex.c
  CC        ../../../core/lib/sensors.c
  CC        ../../../core/lib/settings.c
  CC        ../../../core/lib/trickle-timer.c
  CC        ../../../core/net/ipv6/sicslowpan.c
  CC        ../../../core/net/ipv6/uip6.c
  CC        ../../../core/net/ipv6/uip-ds6.c
  CC        ../../../core/net/ipv6/uip-ds6-nbr.c
  CC        ../../../core/net/ipv6/uip-ds6-route.c
  CC        ../../../core/net/ipv6/uip-icmp6.c
  CC        ../../../core/net/ipv6/uip-nd6.c
  CC        ../../../core/net/ipv6/websocket.c
  CC        ../../../core/net/ipv6/websocket-http-client.c
  CC        ../../../core/net/ip/dhcpc.c
  CC        ../../../core/net/ip/ip64-addr.c
  CC        ../../../core/net/ip/psock.c
  CC        ../../../core/net/ip/resolv.c
  CC        ../../../core/net/ip/simple-udp.c
  CC        ../../../core/net/ip/slipdev.c
  CC        ../../../core/net/ip/tcpip.c
  CC        ../../../core/net/ip/tcp-socket.c
  CC        ../../../core/net/ip/udp-socket.c
  CC        ../../../core/net/ip/uip-debug.c
  CC        ../../../core/net/ip/uiplib.c
  CC        ../../../core/net/ip/uip-nameserver.c
  CC        ../../../core/net/ip/uip-packetqueue.c
  CC        ../../../core/net/ip/uip-split.c
  CC        ../../../core/net/ip/uip-udp-packet.c
  CC        ../../../core/net/rpl/rpl.c
  CC        ../../../core/net/rpl/rpl-dag.c
  CC        ../../../core/net/rpl/rpl-dag-root.c
  CC        ../../../core/net/rpl/rpl-ext-header.c
  CC        ../../../core/net/rpl/rpl-icmp6.c
  CC        ../../../core/net/rpl/rpl-mrhof.c
  CC        ../../../core/net/rpl/rpl-nbr-policy.c
  CC        ../../../core/net/rpl/rpl-ns.c
  CC        ../../../core/net/rpl/rpl-of0.c
  CC        ../../../core/net/rpl/rpl-sdn.c
  CC        ../../../core/net/rpl/rpl-timers.c
  CC        ../../../core/net/linkaddr.c
  CC        ../../../core/net/link-stats.c
  CC        ../../../core/net/nbr-table.c
  CC        ../../../core/net/net-debug.c
  CC        ../../../core/net/netstack.c
  CC        ../../../core/net/packetbuf.c
  CC        ../../../core/net/queuebuf.c
  CC        ../../../core/net/mac/csma.c
  CC        ../../../core/net/mac/frame802154.c
  CC        ../../../core/net/mac/frame802154e-ie.c
  CC        ../../../core/net/mac/framer-802154.c
  CC        ../../../core/net/mac/framer-nullmac.c
  CC        ../../../core/net/mac/mac.c
  CC        ../../../core/net/mac/mac-sequence.c
  CC        ../../../core/net/mac/nordc.c
  CC        ../../../core/net/mac/nullmac.c
  CC        ../../../core/net/mac/nullrdc.c
  CC        ../../../core/net/mac/nullrdc-noframer.c
  CC        ../../../core/net/mac/phase.c
  CC        ../../../core/net/mac/contikimac/contikimac.c
  CC        ../../../core/net/mac/contikimac/contikimac-framer.c
  CC        ../../../core/net/llsec/anti-replay.c
  CC        ../../../core/net/llsec/ccm-star-packetbuf.c
  CC        ../../../core/net/llsec/nullsec.c
cp ../../../tools/empty-symbols.c symbols.c
cp ../../../tools/empty-symbols.h symbols.h
  CC        symbols.c
  CC        ../../../core/net/sdn/sdn-stats.c
  AR        contiki-exp5438.a
msp430-ar: obj_exp5438/print-stats.o: No such file or directory
make: *** [contiki-exp5438.a] Error 1

**Comment by mbaddeley** [comment]
Are you using the 20-bit compiler [here](https://github.com/pksec/msp430-gcc-4.7.3)? You also need to have added the compiler location to your $PATH.

--- edit ---

So I just read the title of this issue properly. Yes, you 100% need 4.7.3! :) This is the 20-bit compiler that the exp5438 nodes need.

--- edit again ---

If you've already tried to update to 4.7.3, and this didn't work, then it's probably because you either...

- Don't have it in your $PATH (like I said above)
- First did `sudo apt install gcc-msp430` <--- this is WRONG! Uninstall!

**Comment by mbaddeley** [comment]
Oh, also try

`make TARGET=exp5438`

**Comment by ghost** [comment]
the second one that u mentioned  " First did `sudo apt install gcc-msp430"`, i didn't do it . i will try again the steps as you mentioned hopefully no errors :)
Thank you very much :)

**Comment by mbaddeley** [comment]
Any problems let me know

**Comment by ghost** [comment]
Hi Michael,
I hope you are doing well. I feel sorry for bothering you again :).
I have had the same errors. I will tell you what the steps I did.
1- I create a new folder in opt by using this command ----> sudo mkdir /opt/compilers.
2- I extract the msp430-gcc-4.7.3 and move it in /opt/compilers.
3- For add the location in /etc/environment by using this command ----> sudo gedit  /etc/ environment , and inside i put this path---> PATH="/opt/compilers/mspgcc-4.7.3/MSP430/bin/"
4- In $HOME, I edited the .bashrc file by using this path----->export PATH=$PATH:/opt/compilers/mspgcc-4.7.3/bin
  
Thank you very much,
Best Regards,

**Comment by mbaddeley** [comment]
You don't need step 3. Remove that.

Just extract msp430-gcc-4.7.3 into any location

`/home/mike/compilers/mspgcc-4.7.3/bin`

and then add this to your ~/.bashrc

`export PATH=$PATH:/home/mike/Compilers/mspgcc-4.7.3/bin`

Then either restart your machine or 

`source ~/.bashrc`

--- edit ---

Also, are you running Ubuntu 64?

**Comment by ghost** [comment]
yes iam running ubuntu 64.
i will try again thank you very much

**Comment by ghost** [comment]
sorry again, but the version does not update into 4.7.3

**Comment by mbaddeley** [comment]
Can you please run:
`msp430-gcc --version`

and

`which msp430-gcc`

and post the results here

**Comment by ghost** [comment]
![screenshot from 2019-02-15 19-36-42](https://user-images.githubusercontent.com/38399265/52870525-20950c00-3159-11e9-83f0-1c2e8a28053f.png)

**Comment by mbaddeley** [comment]
and the other command?

`which msp430-gcc`

also please run 

`echo $PATH`

**Comment by ghost** [comment]
sorry about the second one 
![zehra](https://user-images.githubusercontent.com/38399265/52871395-04926a00-315b-11e9-865e-40a165e893f0.png)

**Comment by ghost** [comment]
did you mean this one?

**Comment by mbaddeley** [comment]
No, just run those two commands in the command line

**Comment by mbaddeley** [comment]
I think one of the issues is you are using instant-contiki, which has msp430-gcc pre installed. It is still using the preinstalled one rather than using the new one you have extracted. We need to find out where the preinstalled one is then delete it. Or at the very least remove it from your path.

**Comment by mbaddeley** [comment]
Essentially...

`echo $PATH`

will show you something like 

`/home/mike/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/mike/Compilers/mspgcc-4.7.3/bin`

but you will probably have two msp430-gcc locations in there. You can do a quick fix by taking out the old msp430-gcc using

`export PATH=<copy-and-paste your path but without the old msp430-gcc>`

I'd recommend using a full linux distro to be honest, particularly if you are going to do any development

**Comment by ghost** [comment]
ok, i will use full linux. To be honest, a week i had have same issue. 
Thank you very much really grateful for your helping.

**Comment by ghost** [comment]
you are right  when i command echo $PATH, the same result u got.

**Comment by mbaddeley** [comment]
1. Clean ubuntu64
2. Install java 8 ppa [http://tipsonubuntu.com/2016/07/31/install-oracle-java-8-9-ubuntu-16-04-linux-mint-18/](url)
3. Download and extract the 4.7.3 compiler
4. Add it to your $PATH
5. Clone uSDN
6. Follow the rest of the instructions for make.

It SHOULD now work! Any more issues, let me know and I'll try to help.

Sorry, I have never tried using the instant contiki vm with uSDN before. The instructions have been based on a full clean ubuntu64 install

**Comment by ghost** [comment]
Thank you very much , actually I will do in full Linux better because one issue in instant contikti  must take care about memory because it is limited and directly crash if u try to download.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by ghost** [comment]
Hi Michael,
Thank you very much, I did in full Linux, and the version of msp430-gcc works perfect. However, I have an issue when Iam running "make" or another command ------->"make TARGET=exp5438" in the controller as well in nodes as shown in the picture below .
Thank you in advance,

**Comment by mbaddeley** [comment]
You've not included the picture?

**Comment by ghost** [comment]
[Image]
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mbaddeley** [comment]
Still no image...

**Comment by ghost** [comment]
Ok I will copy as text

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by ghost** [comment]
zehra@zehra-Lenovo-IdeaPad-Y510P:~/usdn/examples/sdn/controller$ make
using saved target 'exp5438'
obj_exp5438/stats.d=
mkdir obj_exp5438
  CC        ../../../apps/multiflow/multiflow.c
  CC        ../../../apps/atom/atom.c
  CC        ../../../apps/atom/atom-buffer.c
  CC        ../../../apps/atom/atom-net.c
  CC        ../../../apps/atom/atom-sb-usdn.c
  CC        ../../../apps/atom/atom-sb-rpl.c
  CC        ../../../apps/atom/atom-app-route-sp.c
  CC        ../../../apps/atom/atom-app-route-rpl.c
  CC        ../../../apps/atom/atom-app-join-cfg.c
  CC        ../../../platform/exp5438/./msp430.c
  CC        ../../../core/dev/leds.c
  CC        ../../../platform/exp5438/./watchdog.c
  CC        ../../../platform/exp5438/./spix.c
  CC        ../../../dev/cc2420/cc2420.c
  CC        ../../../platform/exp5438/./cc2420-arch.c
  CC        ../../../platform/exp5438/./rtimer-arch.c
  CC        ../../../platform/exp5438/./node-id.c
  CC        ../../../platform/exp5438/./leds-arch.c
  CC        ../../../platform/exp5438/./uart1x.c
  CC        ../../../platform/exp5438/./lcd.c
  CC        ../../../platform/exp5438/./hal_lcd.c
  CC        ../../../platform/exp5438/./hal_lcd_fonts.c
  CC        ../../../platform/exp5438/./duty-cycle-scroller.c
  CC        ../../../core/cfs/cfs-ram.c
  CC        ../../../platform/exp5438/./uart1-putchar.c
  CC        ../../../core/lib/me.c
  CC        ../../../core/lib/me_tabs.c
  CC        ../../../core/dev/slip.c
  CC        ../../../core/lib/crc16.c
  CC        ../../../platform/exp5438/./flash.c
  CC        ../../../platform/exp5438/./clock.c
  CC        ../../../cpu/msp430/./lpm.c
  CC        ../../../core/loader/elfloader.c
  CC        ../../../core/loader/elfloader-msp430.c
  CC        ../../../core/loader/symtab.c
  CC        ../../../core/net/sdn/sdn.c
  CC        ../../../core/net/sdn/sdn-cd.c
  CC        ../../../core/net/sdn/sdn-conf.c
  CC        ../../../core/net/sdn/sdn-ext-header.c
  CC        ../../../core/net/sdn/sdn-ft.c
  CC        ../../../core/net/sdn/sdn-packetbuf.c
  CC        ../../../core/net/sdn/usdn/usdn-adapter.c
  CC        ../../../core/net/sdn/usdn/usdn-driver.c
  CC        ../../../core/net/sdn/usdn/usdn-engine.c
  CC        ../../../core/sys/arg.c
  CC        ../../../core/sys/autostart.c
  CC        ../../../core/sys/compower.c
  CC        ../../../core/sys/ctimer.c
  CC        ../../../core/sys/energest.c
  CC        ../../../core/sys/etimer.c
  CC        ../../../core/sys/log-ng.c
  CC        ../../../core/sys/mt.c
  CC        ../../../core/sys/process.c
  CC        ../../../core/sys/procinit.c
  CC        ../../../core/sys/rtimer.c
  CC        ../../../core/sys/stimer.c
  CC        ../../../core/sys/timer.c
  CC        ../../../core/dev/nullradio.c
  CC        ../../../core/dev/serial-line.c
  CC        ../../../core/lib/aes-128.c
  CC        ../../../core/lib/assert.c
  CC        ../../../core/lib/ccm-star.c
  CC        ../../../core/lib/gcr.c
  CC        ../../../core/lib/ifft.c
  CC        ../../../core/lib/list.c
  CC        ../../../core/lib/memb.c
  CC        ../../../core/lib/mmem.c
  CC        ../../../core/lib/petsciiconv.c
obj_exp5438/stats.o=
  CC        ../../../core/lib/random.c
  CC        ../../../core/lib/ringbuf.c
  CC        ../../../core/lib/ringbufindex.c
  CC        ../../../core/lib/sensors.c
  CC        ../../../core/lib/settings.c
  CC        ../../../core/lib/trickle-timer.c
  CC        ../../../core/net/ipv6/sicslowpan.c
  CC        ../../../core/net/ipv6/uip6.c
  CC        ../../../core/net/ipv6/uip-ds6.c
  CC        ../../../core/net/ipv6/uip-ds6-nbr.c
  CC        ../../../core/net/ipv6/uip-ds6-route.c
  CC        ../../../core/net/ipv6/uip-icmp6.c
  CC        ../../../core/net/ipv6/uip-nd6.c
  CC        ../../../core/net/ipv6/websocket.c
  CC        ../../../core/net/ipv6/websocket-http-client.c
  CC        ../../../core/net/ip/dhcpc.c
  CC        ../../../core/net/ip/ip64-addr.c
  CC        ../../../core/net/ip/psock.c
  CC        ../../../core/net/ip/resolv.c
  CC        ../../../core/net/ip/simple-udp.c
  CC        ../../../core/net/ip/slipdev.c
  CC        ../../../core/net/ip/tcpip.c
  CC        ../../../core/net/ip/tcp-socket.c
  CC        ../../../core/net/ip/udp-socket.c
  CC        ../../../core/net/ip/uip-debug.c
  CC        ../../../core/net/ip/uiplib.c
  CC        ../../../core/net/ip/uip-nameserver.c
  CC        ../../../core/net/ip/uip-packetqueue.c
  CC        ../../../core/net/ip/uip-split.c
  CC        ../../../core/net/ip/uip-udp-packet.c
  CC        ../../../core/net/rpl/rpl.c
  CC        ../../../core/net/rpl/rpl-dag.c
  CC        ../../../core/net/rpl/rpl-dag-root.c
  CC        ../../../core/net/rpl/rpl-ext-header.c
  CC        ../../../core/net/rpl/rpl-icmp6.c
  CC        ../../../core/net/rpl/rpl-mrhof.c
  CC        ../../../core/net/rpl/rpl-nbr-policy.c
  CC        ../../../core/net/rpl/rpl-ns.c
  CC        ../../../core/net/rpl/rpl-of0.c
  CC        ../../../core/net/rpl/rpl-sdn.c
  CC        ../../../core/net/rpl/rpl-timers.c
  CC        ../../../core/net/linkaddr.c
  CC        ../../../core/net/link-stats.c
  CC        ../../../core/net/nbr-table.c
  CC        ../../../core/net/net-debug.c
  CC        ../../../core/net/netstack.c
  CC        ../../../core/net/packetbuf.c
  CC        ../../../core/net/queuebuf.c
  CC        ../../../core/net/mac/csma.c
  CC        ../../../core/net/mac/frame802154.c
  CC        ../../../core/net/mac/frame802154e-ie.c
  CC        ../../../core/net/mac/framer-802154.c
  CC        ../../../core/net/mac/framer-nullmac.c
  CC        ../../../core/net/mac/mac.c
  CC        ../../../core/net/mac/mac-sequence.c
  CC        ../../../core/net/mac/nordc.c
  CC        ../../../core/net/mac/nullmac.c
  CC        ../../../core/net/mac/nullrdc.c
  CC        ../../../core/net/mac/nullrdc-noframer.c
  CC        ../../../core/net/mac/phase.c
  CC        ../../../core/net/mac/contikimac/contikimac.c
  CC        ../../../core/net/mac/contikimac/contikimac-framer.c
  CC        ../../../core/net/llsec/anti-replay.c
  CC        ../../../core/net/llsec/ccm-star-packetbuf.c
  CC        ../../../core/net/llsec/nullsec.c
cp ../../../tools/empty-symbols.c symbols.c
cp ../../../tools/empty-symbols.h symbols.h
  CC        symbols.c
  CC        ../../../core/net/sdn/sdn-stats.c
  AR        contiki-exp5438.a
msp430-ar: obj_exp5438/print-stats.o: No such file or directory
make: *** [contiki-exp5438.a] Error 1
zehra@zehra-Lenovo-IdeaPad-Y510P:~/usdn/examples/sdn/controller$

**Comment by mbaddeley** [comment]
Double check msp version and post here please. If it's correct (4.7.3) then I'll double check the repo tomorrow morning.

`msp430-gcc --version`

I did clone it myself recently though... so should be ok...

**Comment by ghost** [comment]
zehra@zehra-Lenovo-IdeaPad-Y510P:~$ msp430-gcc --version
msp430-gcc (GCC) 4.7.3 20130411 (mspgcc dev 20120911)
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by ghost** [comment]
sorry that i have issue when drag and drop picture in github that not let me post it

**Comment by mbaddeley** [comment]
Are you on master of devel branch?

**Comment by ghost** [comment]
will i change cc in Makefile which located in ....> usdn/cpu/msp430?

**Comment by ghost** [comment]
what different between them?

**Comment by ghost** [comment]
you mean i have install contiki then i will download usdn?

**Comment by mbaddeley** [comment]
no no, contiki is included as part of uSDN. Hang on, I'm trying to debug it this end

**Comment by ghost** [comment]
yes i mean that because i test cooja works fine

**Comment by mbaddeley** [comment]
Try running 

`make clean TARGET=exp5438 && make TARGET=exp5438`

**Comment by ghost** [comment]
same error

**Comment by mbaddeley** [comment]
`you mean i have install contiki then i will download usdn?`

Hang on, do you mean you downloaded contiki as well as usdn?

**Comment by mbaddeley** [comment]
I just tried usdn master branch with a clean install and it compiles ok

**Comment by ghost** [comment]
No I didn’t download contiki

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by mbaddeley** [comment]
try checking out devel branch

To be honest I'm having a hard time thinking of what this could be. I've tried it a number of times on my end with a clean git clone of master and devel, with no issues :/ It seems like on your end the compiler doesn't like sdn-stats.c, but that shouldn't be the case. I can take another look tomorrow morning. 

We will solve this!

**Comment by ghost** [comment]
Ok I will do this one
Thank you very much really appreciate  your helping.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by mbaddeley** [comment]
So the fact it's working my end thinks this is a compiler thing rather than a specific usdn problem... but I'm not entirely sure how, as your compiler appears to be correct... But this is what it should be coming up with:

![image](https://user-images.githubusercontent.com/9554264/52980966-c0aa9980-33d4-11e9-9d69-9c18ba02672b.png)

**Comment by mbaddeley** [comment]
You're on ubuntu 64 correct? What's your make version?

`make --version`

**Comment by ghost** [comment]
Yes Ubuntu 64
GNU Make 3.81

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by mbaddeley** [comment]
hmmm I'm on Make 4.1, but I doubt its an issue - try updating?

**Comment by ghost** [comment]
Ok I will do it

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by mbaddeley** [comment]
So I can see why it doesn't find print-stats on yours, because it's not including sdn-stats.c when it's compiling. However it does on my end (top CC line)... very mysterious...

```
make clean && make
using saved target 'exp5438'
rm -f *~ *core core *.srec \
*.lst *.map \
*.cprg *.bin *.data contiki*.a *.firmware core-labels.S *.ihex *.ini \
*.ce *.co
rm -rf *.exp5438 symbols.c symbols.h
rm -rf obj_exp5438
using saved target 'exp5438'
obj_exp5438/stats.d=
mkdir obj_exp5438
  CC        ../../../core/net/sdn/sdn-stats.c
  CC        ../../../apps/multiflow/multiflow.c
  CC        ../../../apps/atom/atom.c
  CC        ../../../apps/atom/atom-buffer.c
  CC        ../../../apps/atom/atom-net.c
  CC        ../../../apps/atom/atom-sb-usdn.c
  CC        ../../../apps/atom/atom-sb-rpl.c
  CC        ../../../apps/atom/atom-app-route-sp.c
  CC        ../../../apps/atom/atom-app-route-rpl.c
  CC        ../../../apps/atom/atom-app-join-cfg.c
  CC        ../../../platform/exp5438/./msp430.c
  CC        ../../../core/dev/leds.c
  CC        ../../../platform/exp5438/./watchdog.c
  CC        ../../../platform/exp5438/./spix.c
  CC        ../../../dev/cc2420/cc2420.c
  CC        ../../../platform/exp5438/./cc2420-arch.c
  CC        ../../../platform/exp5438/./rtimer-arch.c
  CC        ../../../platform/exp5438/./node-id.c
  CC        ../../../platform/exp5438/./leds-arch.c
  CC        ../../../platform/exp5438/./uart1x.c
  CC        ../../../platform/exp5438/./lcd.c
  CC        ../../../platform/exp5438/./hal_lcd.c
  CC        ../../../platform/exp5438/./hal_lcd_fonts.c
  CC        ../../../platform/exp5438/./duty-cycle-scroller.c
  CC        ../../../core/cfs/cfs-ram.c
  CC        ../../../platform/exp5438/./uart1-putchar.c
  CC        ../../../core/lib/me.c
  CC        ../../../core/lib/me_tabs.c
  CC        ../../../core/dev/slip.c
  CC        ../../../core/lib/crc16.c
  CC        ../../../platform/exp5438/./flash.c
  CC        ../../../platform/exp5438/./clock.c
  CC        ../../../cpu/msp430/./lpm.c
  CC        ../../../core/loader/elfloader.c
  CC        ../../../core/loader/elfloader-msp430.c
  CC        ../../../core/loader/symtab.c
  CC        ../../../core/net/sdn/sdn-conf.c
  CC        ../../../core/net/sdn/sdn-ft.c
  CC        ../../../core/net/sdn/sdn-cd.c
  CC        ../../../core/net/sdn/sdn-packetbuf.c
  CC        ../../../core/net/sdn/sdn-ext-header.c
  CC        ../../../core/net/sdn/sdn.c
  CC        ../../../core/net/sdn/usdn/usdn-adapter.c
  CC        ../../../core/net/sdn/usdn/usdn-driver.c
  CC        ../../../core/net/sdn/usdn/usdn-engine.c
  CC        ../../../core/sys/autostart.c
  CC        ../../../core/sys/stimer.c
  CC        ../../../core/sys/arg.c
  CC        ../../../core/sys/energest.c
  CC        ../../../core/sys/etimer.c
  CC        ../../../core/sys/log-ng.c
  CC        ../../../core/sys/ctimer.c
  CC        ../../../core/sys/compower.c
  CC        ../../../core/sys/process.c
  CC        ../../../core/sys/rtimer.c
  CC        ../../../core/sys/mt.c
  CC        ../../../core/sys/procinit.c
  CC        ../../../core/sys/timer.c
  CC        ../../../core/dev/serial-line.c
  CC        ../../../core/dev/nullradio.c
  CC        ../../../core/lib/settings.c
  CC        ../../../core/lib/mmem.c
  CC        ../../../core/lib/ccm-star.c
  CC        ../../../core/lib/ifft.c
  CC        ../../../core/lib/sensors.c
  CC        ../../../core/lib/ringbufindex.c
  CC        ../../../core/lib/list.c
  CC        ../../../core/lib/aes-128.c
  CC        ../../../core/lib/trickle-timer.c
  CC        ../../../core/lib/print-stats.c
  CC        ../../../core/lib/memb.c
  CC        ../../../core/lib/petsciiconv.c
  CC        ../../../core/lib/gcr.c
  CC        ../../../core/lib/assert.c
  CC        ../../../core/lib/random.c
  CC        ../../../core/lib/ringbuf.c
  CC        ../../../core/net/ipv6/websocket.c
  CC        ../../../core/net/ipv6/uip-icmp6.c
  CC        ../../../core/net/ipv6/uip-ds6.c
  CC        ../../../core/net/ipv6/uip-ds6-route.c
  CC        ../../../core/net/ipv6/uip6.c
  CC        ../../../core/net/ipv6/uip-ds6-nbr.c
  CC        ../../../core/net/ipv6/uip-nd6.c
  CC        ../../../core/net/ipv6/websocket-http-client.c
  CC        ../../../core/net/ipv6/sicslowpan.c
  CC        ../../../core/net/ip/slipdev.c
  CC        ../../../core/net/ip/dhcpc.c
  CC        ../../../core/net/ip/uip-debug.c
  CC        ../../../core/net/ip/uip-packetqueue.c
  CC        ../../../core/net/ip/tcp-socket.c
  CC        ../../../core/net/ip/ip64-addr.c
  CC        ../../../core/net/ip/uip-udp-packet.c
  CC        ../../../core/net/ip/psock.c
  CC        ../../../core/net/ip/tcpip.c
  CC        ../../../core/net/ip/resolv.c
  CC        ../../../core/net/ip/uip-nameserver.c
  CC        ../../../core/net/ip/uip-split.c
  CC        ../../../core/net/ip/udp-socket.c
  CC        ../../../core/net/ip/simple-udp.c
  CC        ../../../core/net/ip/uiplib.c
  CC        ../../../core/net/rpl/rpl-nbr-policy.c
  CC        ../../../core/net/rpl/rpl-of0.c
  CC        ../../../core/net/rpl/rpl-dag.c
  CC        ../../../core/net/rpl/rpl-timers.c
  CC        ../../../core/net/rpl/rpl-ext-header.c
  CC        ../../../core/net/rpl/rpl.c
  CC        ../../../core/net/rpl/rpl-sdn.c
  CC        ../../../core/net/rpl/rpl-mrhof.c
  CC        ../../../core/net/rpl/rpl-ns.c
  CC        ../../../core/net/rpl/rpl-icmp6.c
  CC        ../../../core/net/rpl/rpl-dag-root.c
  CC        ../../../core/net/queuebuf.c
  CC        ../../../core/net/nbr-table.c
  CC        ../../../core/net/packetbuf.c
  CC        ../../../core/net/netstack.c
  CC        ../../../core/net/linkaddr.c
  CC        ../../../core/net/net-debug.c
  CC        ../../../core/net/link-stats.c
  CC        ../../../core/net/mac/framer-nullmac.c
  CC        ../../../core/net/mac/nullmac.c
  CC        ../../../core/net/mac/nullrdc-noframer.c
  CC        ../../../core/net/mac/nordc.c
  CC        ../../../core/net/mac/frame802154e-ie.c
  CC        ../../../core/net/mac/mac-sequence.c
  CC        ../../../core/net/mac/framer-802154.c
  CC        ../../../core/net/mac/csma.c
  CC        ../../../core/net/mac/frame802154.c
  CC        ../../../core/net/mac/mac.c
  CC        ../../../core/net/mac/phase.c
  CC        ../../../core/net/mac/nullrdc.c
  CC        ../../../core/net/mac/contikimac/contikimac.c
  CC        ../../../core/net/mac/contikimac/contikimac-framer.c
  CC        ../../../core/net/llsec/nullsec.c
  CC        ../../../core/net/llsec/anti-replay.c
  CC        ../../../core/net/llsec/ccm-star-packetbuf.c
cp ../../../tools/empty-symbols.c symbols.c
cp ../../../tools/empty-symbols.h symbols.h
  CC        symbols.c
  AR        contiki-exp5438.a
  CC        sdn-controller.c
  CC        ../../../platform/exp5438/./contiki-exp5438-main.c
  LD        sdn-controller.exp5438
rm obj_exp5438/contiki-exp5438-main.o sdn-controller.co

```

**Comment by mbaddeley** [comment]
Also, can you do the following command and copy-paste the result here please?

`echo $PATH`

**Comment by ghost** [comment]
zehra@zehra-Lenovo-IdeaPad-Y510P:~$ echo $PATH
/opt/mspgccx/bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/opt/compilers/mspgcc-4.7.3/bin

**Comment by mbaddeley** [comment]
Why do you have two mspgcc....? Remove the first one from your path. You path should look like this.

`/home/mike/Compilers/mspgcc-.7.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin`

If you take out the mspgccx then I think it will work:

`export PATH=/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/opt/compilers/mspgcc-4.7.3/bin`

**---Note---**

I don't know where the mspgccx environment variable is coming from so to delete it permanently you'll need to find that out, otherwise you will need to run that the `export PATH=...` command each time.

**Comment by ghost** [comment]
It is working the problem of path

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by ghost** [comment]
Thank you very much sorry for bothering you

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by mbaddeley** [comment]
No problem at all!

On 19 Feb 2019 00:07, zahraazakariya <notifications@github.com> wrote:
Thank you very much sorry for bothering you

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by zahraazakariya** [comment]
It is working
Yes the problem of mspgcc

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
