### ISSUE TITLE
A question about routing

### ISSUE THREAD

**Issue by Superspider** [mbaddeley/usdn#4]
When the controller receives FTQ, how does it calculate the path? Is it the Dijkstra algorithm?

**Comment by mbaddeley** [comment]
Yes, although there are two routing implementations on Atom. The first is shortest path routing, the other is a RPL non-storing routing algorithm.
________________________________

**Comment by mbaddeley** [comment]
Ok, so now I get why you were asking this... if you look at atom-conf.h line 94 you'll see:

```
#define ATOM_ROUTING_APPS_USDN { &app_route_rpl } //, &app_route_rpl }
```

This needs to be changed to

```
#define ATOM_ROUTING_APPS_USDN { &app_route_sp } //, &app_route_rpl }
```

Otherwise it will use a centralised RPL-NS routing algorithm rather than shortest path.

**Comment by Superspider** [comment]
Okay, I got it.Thank you very much for your help.
