### ISSUE TITLE
Doubt about this repository and uSDN-NG repo

### ISSUE THREAD

**Issue by davidcawork** [mbaddeley/usdn#6]
Hello!

I had a question as I have been consulting both repositories about uSDN, and it is not clear to me. It would be great if you could give me some guidance on this 😄 

From what I've been seeing there are two uSDN repositories:

- This [one](https://github.com/mbaddeley/usdn), which has the uSDN source code base and has Contiki support.
- This other [one](https://github.com/mbaddeley/usdn-ng), which is being progressively ported from the uSDN source code base to Contiki-NG.

Is this correct? Thank you!

**Comment by mbaddeley** [comment]
Yep this is correct! I tried to port to NG and while it does work, there's
some issues when trying it in cooja with NG :/

Cooja motes seem to crash if there's > 10, so I guess there's memory
corruption in the controller somewhere.

Z1 motes crash at the controller shortly after init. Again this must be
trying to access some bit or memory.

The original uSDN works with the exp5438 motes (which aren't supported in
NG), and should have no issues -- it's just an older OS

Hope this helps!


Michael

**Comment by davidcawork** [comment]
Understood! Thank you very much! I'll start by looking at this repository then 😄
